### ISSUE TITLE
general.World.java inutile

### ISSUE THREAD

**Issue by PolariTOON** [TeleGD/tgd-projet_2018#1]
La classe `World` du paquet `general` n'est utilisée par aucune autre classe.
De plus, la plupart de ses méthodes ne sont pas écrites.
Je pense qu'il s'agit d'une ancienne version de la classe `WorldPlateau` du paquet `hub`.

Est-il prévu de s'en servir dans un autre cadre ? La classe `WorldPlateau` m'a l'air de suffire.

Je propose de supprimer le fichier si rien n'est envisagé.

**Comment by DavidForlen** [comment]
Il n'y a en effet aucunes références à ce world ailleurs dans le code, il faudra tester si sa suppression n'impacte rien.

**Comment by PolariTOON** [comment]
Le fichier a été supprimé dans https://github.com/TeleGD/tgd-projet_2018/commit/e8185a86311a544c06519f52f99e8559374bbaef.
